In [5]:
import numpy as np

In [6]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
arr= np.arange(0,11)

In [8]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [10]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [12]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [13]:
arr *  100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [14]:
arr/arr

<ipython-input-14-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [16]:
#nan=not a number
arr1 = np.arange(0,11)

# 

In [17]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
my_list = [1,2,3]

In [19]:
np.array(my_list)

array([1, 2, 3])

In [20]:
my_mat= [[1,2,3],[4,5,6],[7,8,9]]

In [21]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [24]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [26]:
#identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [38]:
np.random.randint(1,100,13)

array([93, 55, 70, 34, 52, 60, 84, 89, 24, 91, 26, 69, 48])

In [39]:
np.random.randn(4,4)

array([[ 1.32310602, -0.07475681, -0.5066698 ,  1.06870363],
       [ 2.28896671, -1.10003598, -0.87355318,  0.84887639],
       [-0.62914423,  0.16837173, -0.57409063, -0.15995697],
       [-1.90256505,  1.93769619, -1.5165901 ,  2.42280317]])

In [40]:
arr.reshape(3,4)

ValueError: cannot reshape array of size 11 into shape (3,4)

In [43]:
# for min value position
arr2= np.arange(100)

In [44]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [45]:
arr2.reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [46]:
arr2.max()

99

In [47]:
arr2.min()

0

In [51]:
arr3 =np.random.randint(0,101,50)

### 

arr3

In [52]:
arr3

array([ 4, 10, 36,  7, 65, 77, 53, 76, 75, 62, 27, 93, 86, 67, 43, 21, 21,
       14, 23,  0, 90, 42, 40, 69, 85, 99, 63, 29, 94, 81, 81, 50, 40, 81,
       11,  1, 69, 46, 52, 76, 76, 69, 66, 35, 84, 37, 46, 68,  9, 60])

In [53]:
arr3.min()

0

In [54]:
arr3.max()

99

In [55]:
arr3.argmin()

19

In [56]:
arr3.argmax()

25

In [57]:
arr3.shape

(50,)

In [58]:
arr3.reshape(5,10)

array([[ 4, 10, 36,  7, 65, 77, 53, 76, 75, 62],
       [27, 93, 86, 67, 43, 21, 21, 14, 23,  0],
       [90, 42, 40, 69, 85, 99, 63, 29, 94, 81],
       [81, 50, 40, 81, 11,  1, 69, 46, 52, 76],
       [76, 69, 66, 35, 84, 37, 46, 68,  9, 60]])

In [61]:
from numpy.random import randint

In [62]:
randint(0,100,50)

array([48, 78, 52, 37, 48, 73, 83, 35, 26, 70,  4, 41, 40, 93, 86, 43, 30,
        6, 59, 39, 50, 91, 62, 27, 53, 10, 30, 69, 37, 43, 46, 32, 55, 39,
       69, 26, 74,  3, 34, 17, 90,  3, 33, 97,  0, 91, 56, 62, 71, 62])